# Generated by Django 5.2.9 on 2026-01-04 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Board name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Board description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the board was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the board was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this board', on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('scheduled_task_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Scheduled task title', max_length=255)),
                ('description', models.TextField(help_text='Task description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', help_text='Task status', max_length=20)),
                ('scheduled_time', models.DateTimeField(db_index=True, help_text='When this task should be processed')),
                ('recurrence_pattern', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], db_index=True, default='ONCE', help_text='How often this task should recur', max_length=50)),
                ('processing_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Processed'), (2, 'Failed')], db_index=True, default=0, help_text='Processing status for background worker')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the scheduled task was created')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the task was processed', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this scheduled task', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Task title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed task description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], db_index=True, default='PENDING', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', help_text='Task priority level', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, help_text='Task due date and time', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Users assigned to this task', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(help_text='Board this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_manager.board')),
                ('created_by', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_log_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('BOARD_CREATED', 'Board Created'), ('BOARD_UPDATED', 'Board Updated'), ('BOARD_DELETED', 'Board Deleted'), ('SCHEDULED_TASK_CREATED', 'Scheduled Task Created')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent of the request', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', '-created_at'], name='task_manage_action__c337ed_idx'), models.Index(fields=['user', '-created_at'], name='task_manage_user_id_d03050_idx'), models.Index(fields=['-created_at'], name='task_manage_created_c2875f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['created_by', 'created_at'], name='task_manage_created_5ce2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['processing_status', 'scheduled_time'], name='task_manage_process_a7c6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['scheduled_time', 'processing_status'], name='task_manage_schedul_46f541_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['created_by', 'scheduled_time'], name='task_manage_created_e8ca91_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'status', '-created_at'], name='task_manage_board_i_2d58ee_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-created_at'], name='task_manage_status_12af69_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'due_date'], name='task_manage_priorit_46bd75_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'status'], name='task_manage_created_dba7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='task_manage_status_503050_idx'),
        ),
    ]
