# Generated by Django 5.2.9 on 2026-01-04 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Users who will be assigned to tasks created from this scheduled task', related_name='assigned_scheduled_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Board this scheduled task will create tasks in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='task_manager.board'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='due_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Due date for tasks created from this scheduled task', null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', help_text='Priority for tasks created from this scheduled task', max_length=10),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['board', 'scheduled_time'], name='task_manage_board_i_dfe7a1_idx'),
        ),
    ]
