# Generated by Django 5.2.9 on 2026-01-06 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_scheduledtask_assigned_to_scheduledtask_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='scheduled_task_id',
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('daily_stats_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date for which stats are aggregated')),
                ('tasks_created', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='task_manage_date_7cecee_idx')],
            },
        ),
    ]
