# Generated by Django 5.2.9 on 2025-12-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_scheduledtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
