# Generated by Django 5.2.9 on 2026-01-04 11:11

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(db_index=True, max_length=100)),
                ('owner_email', models.EmailField(db_index=True, help_text='Email of the organization owner', max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Kill-switch for the tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_email', models.EmailField(db_index=True, help_text='Email for billing', max_length=254)),
                ('billing_address', models.TextField(help_text='Address for billing')),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email_domain', models.CharField(db_index=True, help_text="Email domain allowed for signup (e.g., 'company.com')", max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Kill-switch for the tenant')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_index=True, max_length=10)),
                ('stripe_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('next_payment_date', models.DateField(db_index=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('subscription_plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('IND', 'Indian Rupee')], db_index=True, default='USD', max_length=3)),
                ('max_users', models.IntegerField(default=5)),
                ('max_tasks', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['currency', 'price'], name='organizatio_currenc_09abd6_idx')],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'created_at'], name='organizatio_is_acti_a02541_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['owner_email', 'is_active'], name='organizatio_owner_e_d85d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_active', 'end_date'], name='organizatio_is_acti_b71b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['billing_cycle', 'is_active'], name='organizatio_billing_ea723a_idx'),
        ),
    ]
