# Generated by Django 5.2.9 on 2026-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email_domain',
            field=models.CharField(db_index=True, help_text="Email domain allowed for sisgnup (e.g., 'company.com')", max_length=255),
        ),
    ]
