# Generated by Django 5.2.9 on 2026-01-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_email_domain'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_is_acti_a02541_idx',
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'business_name'], name='organizatio_is_acti_205d8b_idx'),
        ),
    ]
