"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS", ".localhost.com,localhost.com,.localhost,localhost,127.0.0.1"
).split(",")
# Ensure .localhost is included for subdomain support (e.g., abc.localhost)
if ".localhost" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".localhost")

# Basic Security Settings
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True

# Request Size Limits
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", "10485760")
)  # 10 MB default
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.getenv("DATA_UPLOAD_MAX_NUMBER_FIELDS", "1000"))


SHARED_APPS = (
    "django_tenants",
    "organizations",
    "accounts",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admin",
    "django.contrib.auth",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_q",
    "notifications",
)

TENANT_APPS = (
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.admin",
    "rest_framework",
    "task_manager",
)

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

TENANT_MODEL = "organizations.Organization"
TENANT_DOMAIN_MODEL = "organizations.Domain"

# Standard Middleware + Custom Checks
MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


AUTH_USER_MODEL = "accounts.UserAccount"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv("DATABASE_NAME"),
        "USER": os.getenv("DATABASE_USER"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),
        "HOST": os.getenv("DATABASE_HOST"),
        "PORT": int(os.getenv("DATABASE_PORT", "5432")),
        "CONN_MAX_AGE": 0,
        "OPTIONS": {
            "options": f"-c timezone={os.getenv('DATABASE_TIMEZONE')}",
        },
    }
}

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE")

USE_I18N = True

USE_TZ = True


STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("accounts.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": [
        # 1. Limits unauthenticated users (e.g., stops brute-forcing login)
        "rest_framework.throttling.AnonRateThrottle",
        # 2. Limits authenticated users (e.g., stops API spam)
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("THROTTLE_ANON_RATE", "10/minute"),
        "user": os.getenv("THROTTLE_USER_RATE", "100/minute"),
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": int(os.getenv("PAGE_SIZE", "20")),
    "PAGE_SIZE_QUERY_PARAM": os.getenv("PAGE_SIZE_QUERY_PARAM", "page_size"),
    "MAX_PAGE_SIZE": int(os.getenv("MAX_PAGE_SIZE", "100")),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", "60"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", "1"))
    ),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "user_id",  # Match our custom primary key field
    "USER_ID_CLAIM": "user_id",  # Token claim name
    "UPDATE_LAST_LOGIN": True,  # Update last_login on token refresh
    "ROTATE_REFRESH_TOKENS": True,  # Rotate refresh token on use
    "BLACKLIST_AFTER_ROTATION": True,  # Blacklist old tokens after rotation
}

# Multi-tenant Domain Configuration
BASE_DOMAIN = os.getenv("BASE_DOMAIN", "localhost")
"""
Base domain for tenant subdomains.
Examples:
- Development: "localhost"
- Production: "app.com"
- Staging: "staging.app.com"
"""

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN")

# CloudFront Configuration (for serving files via CDN)
AWS_CLOUDFRONT_DOMAIN = os.getenv(
    "AWS_CLOUDFRONT_DOMAIN", ""
)  # e.g., d1234567890.cloudfront.net
USE_CLOUDFRONT = os.getenv("USE_CLOUDFRONT", "False").lower() == "true"

# S3 File Access Configuration
AWS_DEFAULT_ACL = os.getenv("AWS_DEFAULT_ACL")  # Keep files private
AWS_S3_FILE_OVERWRITE = os.getenv(
    "AWS_S3_FILE_OVERWRITE"
)  # Don't overwrite files with same name

# Presigned URL Configuration (for uploads only)
AWS_PRESIGNED_URL_EXPIRATION = int(os.getenv("AWS_PRESIGNED_URL_EXPIRATION"))  # 1 hour

# File Upload Limits
MAX_UPLOAD_SIZE = int(os.getenv("MAX_UPLOAD_SIZE"))

# Allowed file types: Images, Text, PDF, Word documents
ALLOWED_FILE_TYPES = [
    # Images
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/gif",
    "image/webp",
    # PDF
    "application/pdf",
    # Word Documents
    "application/msword",  # .doc
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",  # .docx
    # Text files
    "text/plain",  # .txt
]

# Logging Configuration
# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

# Django Q2 Configuration
Q_CLUSTER = {
    "name": os.getenv("Q_CLUSTER_NAME", "TaskFlow"),
    "workers": int(os.getenv("Q_WORKERS", "2")),
    "recycle": int(os.getenv("Q_RECYCLE", "500")),
    "timeout": int(os.getenv("Q_TIMEOUT", "60")),
    "retry": int(os.getenv("Q_RETRY", "120")),
    "queue_limit": int(os.getenv("Q_QUEUE_LIMIT", "50")),
    "bulk": int(os.getenv("Q_BULK", "10")),
    "orm": os.getenv("Q_ORM", "default"),  # Use database as broker
    "catch_up": os.getenv("Q_CATCH_UP", "False").lower() == "true",
    "max_attempts": int(os.getenv("Q_MAX_ATTEMPTS", "3")),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "django.log",
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "django_errors.log",
            "maxBytes": 1024 * 1024 * 10,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file", "error_file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file", "error_file"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        # Application loggers
        "accounts": {
            "handlers": ["console", "file", "error_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "task_manager": {
            "handlers": ["console", "file", "error_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "organizations": {
            "handlers": ["console", "file", "error_file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}
